import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { mkdir, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join, normalize, resolve, sep } from 'node:path';
import type { Readable } from 'node:stream';
import {
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
  DeleteObjectCommand,
} from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { getConfig } from '../config.js';
import { AppError, ERROR_CODES, forbidden, notFound } from './errors.js';

/**
 * File storage behind one interface with two implementations.
 *
 * `local` exists so the whole platform runs on a laptop or a single VM with no
 * object store at all — which is the realistic first deployment for a district
 * pilot. `s3` is the same contract against MinIO, NIC's object storage, or AWS,
 * and is what a state-wide rollout uses.
 *
 * Both keep every file private. Nothing is ever served from a permanent public
 * URL; readers get a signed link that expires, so a photograph of a child
 * cannot be hotlinked or indexed after the activity is unpublished.
 */

export interface UploadTicket {
  key: string;
  uploadUrl: string;
  method: 'PUT' | 'POST';
  headers: Record<string, string>;
  expiresInSeconds: number;
}

export interface StorageDriver {
  readonly kind: 'local' | 's3';
  createUploadTicket(input: {
    key: string;
    contentType: string;
    sizeBytes: number;
  }): Promise<UploadTicket>;
  getSignedReadUrl(key: string, ttlSeconds?: number): Promise<string>;
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  delete(key: string): Promise<void>;
  /** Only implemented by the local driver; S3 serves bytes directly. */
  createReadStream?(
    key: string,
  ): Promise<{ stream: Readable; contentType: string; sizeBytes: number }>;
}

/**
 * Builds the object key.
 *
 * Scoped by school and date so that a bucket listing is navigable by a human,
 * and suffixed with a UUID so that two teachers uploading `IMG_0001.jpg` at the
 * same moment cannot collide or overwrite each other.
 */
export function buildStorageKey(input: {
  scope: string;
  purpose: 'activity' | 'consent' | 'evidence';
  contentType: string;
}): string {
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
  const extension = EXTENSION_BY_TYPE[input.contentType] ?? 'bin';
  return `${input.purpose}/${input.scope}/${yyyy}/${mm}/${randomUUID()}.${extension}`;
}

const EXTENSION_BY_TYPE: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'application/pdf': 'pdf',
};

/** Keys are generated by this module; anything else is rejected before it reaches a filesystem. */
const KEY_PATTERN = /^[a-z]+\/[A-Za-z0-9_-]+\/\d{4}\/\d{2}\/[A-Za-z0-9-]+\.[a-z0-9]{1,5}$/;

export function assertValidKey(key: string): void {
  if (!KEY_PATTERN.test(key) || key.includes('..')) {
    throw new AppError(400, ERROR_CODES.VALIDATION_FAILED, 'Malformed storage key');
  }
}

// ---------------------------------------------------------------------------
// Local driver
// ---------------------------------------------------------------------------

interface SignedPayload {
  key: string;
  op: 'read' | 'write';
  exp: number;
  contentType?: string;
  maxBytes?: number;
}

function sign(payload: SignedPayload, secret: string): string {
  const body = Buffer.from(JSON.stringify(payload)).toString('base64url');
  const mac = createHmac('sha256', secret).update(body).digest('base64url');
  return `${body}.${mac}`;
}

export function verifySignedStorageToken(
  token: string,
  secret: string,
  op: 'read' | 'write',
): SignedPayload {
  const [body, mac] = token.split('.');
  if (!body || !mac) throw forbidden('Invalid file token');
  const expected = createHmac('sha256', secret).update(body).digest('base64url');
  const givenBuffer = Buffer.from(mac);
  const expectedBuffer = Buffer.from(expected);
  if (
    givenBuffer.length !== expectedBuffer.length ||
    !timingSafeEqual(givenBuffer, expectedBuffer)
  ) {
    throw forbidden('Invalid file token');
  }
  let payload: SignedPayload;
  try {
    payload = JSON.parse(Buffer.from(body, 'base64url').toString('utf8')) as SignedPayload;
  } catch {
    throw forbidden('Invalid file token');
  }
  if (payload.op !== op) throw forbidden('File token is for a different operation');
  if (payload.exp < Math.floor(Date.now() / 1000)) throw forbidden('This link has expired');
  assertValidKey(payload.key);
  return payload;
}

class LocalStorageDriver implements StorageDriver {
  readonly kind = 'local' as const;

  constructor(
    private readonly rootDir: string,
    private readonly apiBaseUrl: string,
    private readonly secret: string,
    private readonly defaultTtl: number,
  ) {}

  private pathFor(key: string): string {
    assertValidKey(key);
    const root = resolve(this.rootDir);
    const full = resolve(join(root, normalize(key)));
    // Belt and braces: the key pattern already forbids traversal, but a
    // filesystem write is not the place to rely on a single check.
    if (full !== root && !full.startsWith(root + sep)) {
      throw forbidden('Refusing to access a path outside the storage root');
    }
    return full;
  }

  async createUploadTicket(input: {
    key: string;
    contentType: string;
    sizeBytes: number;
  }): Promise<UploadTicket> {
    const exp = Math.floor(Date.now() / 1000) + this.defaultTtl;
    const token = sign(
      {
        key: input.key,
        op: 'write',
        exp,
        contentType: input.contentType,
        maxBytes: input.sizeBytes,
      },
      this.secret,
    );
    return {
      key: input.key,
      uploadUrl: `${this.apiBaseUrl}/v1/files/upload?token=${encodeURIComponent(token)}`,
      method: 'PUT',
      headers: { 'content-type': input.contentType },
      expiresInSeconds: this.defaultTtl,
    };
  }

  async getSignedReadUrl(key: string, ttlSeconds?: number): Promise<string> {
    assertValidKey(key);
    const exp = Math.floor(Date.now() / 1000) + (ttlSeconds ?? this.defaultTtl);
    const token = sign({ key, op: 'read', exp }, this.secret);
    return `${this.apiBaseUrl}/v1/files/download?token=${encodeURIComponent(token)}`;
  }

  async put(key: string, body: Buffer, _contentType: string): Promise<void> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }

  async createReadStream(
    key: string,
  ): Promise<{ stream: Readable; contentType: string; sizeBytes: number }> {
    const path = this.pathFor(key);
    let info: Awaited<ReturnType<typeof stat>>;
    try {
      info = await stat(path);
    } catch {
      throw notFound('File not found');
    }
    const extension = key.split('.').pop() ?? '';
    const contentType =
      Object.entries(EXTENSION_BY_TYPE).find(([, ext]) => ext === extension)?.[0] ??
      'application/octet-stream';
    return { stream: createReadStream(path), contentType, sizeBytes: info.size };
  }
}

// ---------------------------------------------------------------------------
// S3 driver
// ---------------------------------------------------------------------------

class S3StorageDriver implements StorageDriver {
  readonly kind = 's3' as const;

  constructor(
    private readonly client: S3Client,
    private readonly bucket: string,
    private readonly defaultTtl: number,
  ) {}

  async createUploadTicket(input: {
    key: string;
    contentType: string;
    sizeBytes: number;
  }): Promise<UploadTicket> {
    assertValidKey(input.key);
    const command = new PutObjectCommand({
      Bucket: this.bucket,
      Key: input.key,
      ContentType: input.contentType,
      ContentLength: input.sizeBytes,
    });
    const uploadUrl = await getSignedUrl(this.client, command, { expiresIn: this.defaultTtl });
    return {
      key: input.key,
      uploadUrl,
      method: 'PUT',
      headers: {
        'content-type': input.contentType,
        'content-length': String(input.sizeBytes),
      },
      expiresInSeconds: this.defaultTtl,
    };
  }

  async getSignedReadUrl(key: string, ttlSeconds?: number): Promise<string> {
    assertValidKey(key);
    return getSignedUrl(this.client, new GetObjectCommand({ Bucket: this.bucket, Key: key }), {
      expiresIn: ttlSeconds ?? this.defaultTtl,
    });
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    assertValidKey(key);
    await this.client.send(
      new PutObjectCommand({ Bucket: this.bucket, Key: key, Body: body, ContentType: contentType }),
    );
  }

  async delete(key: string): Promise<void> {
    assertValidKey(key);
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }
}

let driver: StorageDriver | null = null;

export function getStorage(): StorageDriver {
  if (driver) return driver;
  const config = getConfig();
  if (config.STORAGE_DRIVER === 's3') {
    const client = new S3Client({
      region: config.S3_REGION ?? 'ap-south-1',
      endpoint: config.S3_ENDPOINT,
      forcePathStyle: config.S3_FORCE_PATH_STYLE,
      credentials:
        config.S3_ACCESS_KEY_ID && config.S3_SECRET_ACCESS_KEY
          ? {
              accessKeyId: config.S3_ACCESS_KEY_ID,
              secretAccessKey: config.S3_SECRET_ACCESS_KEY,
            }
          : undefined,
    });
    driver = new S3StorageDriver(
      client,
      config.S3_BUCKET ?? 'balsanskar',
      config.SIGNED_URL_TTL_SECONDS,
    );
  } else {
    driver = new LocalStorageDriver(
      config.STORAGE_LOCAL_DIR,
      config.PUBLIC_API_BASE_URL,
      config.JWT_SECRET,
      config.SIGNED_URL_TTL_SECONDS,
    );
  }
  return driver;
}

/** Test helper. */
export function resetStorage(): void {
  driver = null;
}
